AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - './tmp/**/*.rb'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - './spec/**/*_spec.rb'

Naming/FileName:
  Exclude:
    - 'lib/clickhouse-rails.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 97

Style/FrozenStringLiteralComment:
  Enabled: false
